modLoader = "javafml"
loaderVersion = "[37,)"
license = "All rights reserved"

[[mods]]
modId = "bookshelf"
version = "${file.jarVersion}"
displayName = "Example Mod"
credits = "Thanks for this example mod goes to Java"
authors = "Love, Cheese and small house plants"
description = '''
'''